Front component
wp-media/rocketcdn-plugin pull request #6
Opened 2021-12-01 21:41 UTC by Tabrisrp

This PR adds the front-side component:
- URLs rewriting with the CDN URL
- Preconnect to the CDN URL in the WP resource hints

2021-12-02 15:16 UTC, iCaspar requested changes
I'm not hard-set on these suggestions, but for consideration/discussion.

2021-12-02 15:16 UTC, iCaspar commented on src/Front/CDN.php
> +		 * @since 3.8.7
Should this be 1.0 (or omit @since, see above)?

2021-12-02 15:16 UTC, iCaspar commented on src/Front/CDN.php
> +	private function rewrite( string $html ): string {
The private methods here will be more testable if they can be extracted to a couple other smaller classes:
`Rewriter` class could expose `rewrite()` and `rewrite_srcset()`.
`PathHelper` class could expose the other url/path transformation logic methods.

(The CDN class would be basically a controller without any real logic to test.)

2021-12-02 15:16 UTC, iCaspar commented on src/Front/ServiceProvider.php
> +	public function register() {
If you go with the class extractions above, this would need to be changed to do the injections.

2021-12-03 19:38 UTC, iCaspar commented on src/Front/CDN.php
> +	private function rewrite( string $html ): string {
Per discussion, we'll split these out later if we need to.

2021-12-03 19:38 UTC, iCaspar approved these changes

2021-12-09 17:58 UTC, piotrbak commented
@Tabrisrp It doesn't look like I have enough permissions to move this PR to the next sprint. Could you move it to 45th?

2021-12-09 19:18 UTC, merged